// currencies-data.js
module.exports = {
    "AED": {"ua": "Дирхам ОАЕ", "en": "UAE Dirham"},
    "AFN": {"ua": "Афганський афгані", "en": "Afghan Afghani"},
    "ALL": {"ua": "Албанський лек", "en": "Albanian Lek"},
    "AMD": {"ua": "Вірменський драм", "en": "Armenian Dram"},
    "ANG": {"ua": "Нідерландський антильський гульден", "en": "Netherlands Antillean Guilder"},
    "AOA": {"ua": "Ангольська кванза", "en": "Angolan Kwanza"},
    "ARS": {"ua": "Аргентинський песо", "en": "Argentine Peso"},
    "AUD": {"ua": "Австралійський долар", "en": "Australian Dollar"},
    "AWG": {"ua": "Арубський флорин", "en": "Aruban Florin"},
    "AZN": {"ua": "Азербайджанський манат", "en": "Azerbaijani Manat"},
    "BAM": {"ua": "Конвертована марка Боснії та Герцеговини", "en": "Bosnia-Herzegovina Convertible Mark"},
    "BBD": {"ua": "Барбадоський долар", "en": "Barbadian Dollar"},
    "BDT": {"ua": "Бангладеська така", "en": "Bangladeshi Taka"},
    "BGN": {"ua": "Болгарський лев", "en": "Bulgarian Lev"},
    "BHD": {"ua": "Бахрейнський динар", "en": "Bahraini Dinar"},
    "BIF": {"ua": "Бурундійський франк", "en": "Burundian Franc"},
    "BMD": {"ua": "Бермудський долар", "en": "Bermudian Dollar"},
    "BND": {"ua": "Брунейський долар", "en": "Brunei Dollar"},
    "BOB": {"ua": "Болівійський болівіано", "en": "Bolivian Boliviano"},
    "BRL": {"ua": "Бразильський реал", "en": "Brazilian Real"},
    "BSD": {"ua": "Багамський долар", "en": "Bahamian Dollar"},
    "BTN": {"ua": "Бутанський нгултрум", "en": "Bhutanese Ngultrum"},
    "BWP": {"ua": "Ботсванська пула", "en": "Botswanan Pula"},
    "BYN": {"ua": "Білоруський рубль", "en": "Belarusian Ruble"},
    "BZD": {"ua": "Белізький долар", "en": "Belize Dollar"},
    "CAD": {"ua": "Канадський долар", "en": "Canadian Dollar"},
    "CDF": {"ua": "Конголезький франк", "en": "Congolese Franc"},
    "CHF": {"ua": "Швейцарський франк", "en": "Swiss Franc"},
    "CLP": {"ua": "Чилійський песо", "en": "Chilean Peso"},
    "CNY": {"ua": "Китайський юань", "en": "Chinese Yuan"},
    "COP": {"ua": "Колумбійський песо", "en": "Colombian Peso"},
    "CRC": {"ua": "Коста-риканський колон", "en": "Costa Rican Colón"},
    "CUC": {"ua": "Кубинський конвертований песо", "en": "Cuban Convertible Peso"},
    "CUP": {"ua": "Кубинський песо", "en": "Cuban Peso"},
    "CVE": {"ua": "Ескудо Кабо-Верде", "en": "Cape Verdean Escudo"},
    "CZK": {"ua": "Чеська крона", "en": "Czech Koruna"},
    "DJF": {"ua": "Джибутійський франк", "en": "Djiboutian Franc"},
    "DKK": {"ua": "Данська крона", "en": "Danish Krone"},
    "DOP": {"ua": "Домініканський песо", "en": "Dominican Peso"},
    "DZD": {"ua": "Алжирський динар", "en": "Algerian Dinar"},
    "EGP": {"ua": "Єгипетський фунт", "en": "Egyptian Pound"},
    "ERN": {"ua": "Еритрейська накфа", "en": "Eritrean Nakfa"},
    "ETB": {"ua": "Ефіопський бир", "en": "Ethiopian Birr"},
    "EUR": {"ua": "Євро", "en": "Euro"},
    "FJD": {"ua": "Фіджійський долар", "en": "Fijian Dollar"},
    "FKP": {"ua": "Фунт Фолклендських островів", "en": "Falkland Islands Pound"},
    "GBP": {"ua": "Британський фунт", "en": "British Pound"},
    "GEL": {"ua": "Грузинський ларі", "en": "Georgian Lari"},
    "GHS": {"ua": "Ганський седі", "en": "Ghanaian Cedi"},
    "GIP": {"ua": "Гібралтарський фунт", "en": "Gibraltar Pound"},
    "GMD": {"ua": "Гамбійський даласі", "en": "Gambian Dalasi"},
    "GNF": {"ua": "Гвінейський франк", "en": "Guinean Franc"},
    "GTQ": {"ua": "Гватемальський кетсаль", "en": "Guatemalan Quetzal"},
    "GYD": {"ua": "Гаянський долар", "en": "Guyanaese Dollar"},
    "HKD": {"ua": "Гонконгський долар", "en": "Hong Kong Dollar"},
    "HNL": {"ua": "Гондураська лемпіра", "en": "Honduran Lempira"},
    "HRK": {"ua": "Хорватська куна", "en": "Croatian Kuna"},
    "HTG": {"ua": "Гаїтянський гурд", "en": "Haitian Gourde"},
    "HUF": {"ua": "Угорський форинт", "en": "Hungarian Forint"},
    "IDR": {"ua": "Індонезійська рупія", "en": "Indonesian Rupiah"},
    "ILS": {"ua": "Ізраїльський новий шекель", "en": "Israeli New Shekel"},
    "INR": {"ua": "Індійська рупія", "en": "Indian Rupee"},
    "IQD": {"ua": "Іракський динар", "en": "Iraqi Dinar"},
    "IRR": {"ua": "Іранський ріал", "en": "Iranian Rial"},
    "ISK": {"ua": "Ісландська крона", "en": "Icelandic Króna"},
    "JMD": {"ua": "Ямайський долар", "en": "Jamaican Dollar"},
    "JOD": {"ua": "Йорданський динар", "en": "Jordanian Dinar"},
    "JPY": {"ua": "Японська єна", "en": "Japanese Yen"},
    "KES": {"ua": "Кенійський шилінг", "en": "Kenyan Shilling"},
    "KGS": {"ua": "Киргизький сом", "en": "Kyrgystani Som"},
    "KHR": {"ua": "Камбоджійський рієль", "en": "Cambodian Riel"},
    "KMF": {"ua": "Коморський франк", "en": "Comorian Franc"},
    "KRW": {"ua": "Південнокорейська вона", "en": "South Korean Won"},
    "KWD": {"ua": "Кувейтський динар", "en": "Kuwaiti Dinar"},
    "KYD": {"ua": "Долар Кайманових островів", "en": "Cayman Islands Dollar"},
    "KZT": {"ua": "Казахстанський тенге", "en": "Kazakhstani Tenge"},
    "LAK": {"ua": "Лаоський кіп", "en": "Laotian Kip"},
    "LBP": {"ua": "Ліванський фунт", "en": "Lebanese Pound"},
    "LKR": {"ua": "Шрі-ланкійська рупія", "en": "Sri Lankan Rupee"},
    "LRD": {"ua": "Ліберійський долар", "en": "Liberian Dollar"},
    "LSL": {"ua": "Лесотський лоті", "en": "Lesotho Loti"},
    "LYD": {"ua": "Лівійський динар", "en": "Libyan Dinar"},
    "MAD": {"ua": "Марокканський дирхам", "en": "Moroccan Dirham"},
    "MDL": {"ua": "Молдовський лей", "en": "Moldovan Leu"},
    "MGA": {"ua": "Малагасійський аріарі", "en": "Malagasy Ariary"},
    "MKD": {"ua": "Македонський денар", "en": "Macedonian Denar"},
    "MMK": {"ua": "М'янманський к'ят", "en": "Myanmar Kyat"},
    "MNT": {"ua": "Монгольський тугрик", "en": "Mongolian Tugrik"},
    "MOP": {"ua": "Патака Макао", "en": "Macanese Pataca"},
    "MUR": {"ua": "Маврикійська рупія", "en": "Mauritian Rupee"},
    "MVR": {"ua": "Мальдівська руфія", "en": "Maldivian Rufiyaa"},
    "MWK": {"ua": "Малавійська квача", "en": "Malawian Kwacha"},
    "MXN": {"ua": "Мексиканський песо", "en": "Mexican Peso"},
    "MYR": {"ua": "Малайзійський рингіт", "en": "Malaysian Ringgit"},
    "MZN": {"ua": "Мозамбіцький метикал", "en": "Mozambican Metical"},
    "NAD": {"ua": "Намібійський долар", "en": "Namibian Dollar"},
    "NGN": {"ua": "Нігерійська наїра", "en": "Nigerian Naira"},
    "NIO": {"ua": "Нікарагуанська кордоба", "en": "Nicaraguan Córdoba"},
    "NOK": {"ua": "Норвезька крона", "en": "Norwegian Krone"},
    "NPR": {"ua": "Непальська рупія", "en": "Nepalese Rupee"},
    "NZD": {"ua": "Новозеландський долар", "en": "New Zealand Dollar"},
    "OMR": {"ua": "Оманський ріал", "en": "Omani Rial"},
    "PAB": {"ua": "Панамський бальбоа", "en": "Panamanian Balboa"},
    "PEN": {"ua": "Перуанський соль", "en": "Peruvian Sol"},
    "PGK": {"ua": "Кіна Папуа-Нової Гвінеї", "en": "Papua New Guinean Kina"},
    "PHP": {"ua": "Філіппінський песо", "en": "Philippine Peso"},
    "PKR": {"ua": "Пакистанська рупія", "en": "Pakistani Rupee"},
    "PLN": {"ua": "Польський злотий", "en": "Polish Złoty"},
    "PYG": {"ua": "Парагвайський гуарані", "en": "Paraguayan Guarani"},
    "QAR": {"ua": "Катарський ріал", "en": "Qatari Riyal"},
    "RON": {"ua": "Румунський лей", "en": "Romanian Leu"},
    "RSD": {"ua": "Сербський динар", "en": "Serbian Dinar"},
    "RUB": {"ua": "Російський рубль", "en": "Russian Ruble"},
    "RWF": {"ua": "Руандійський франк", "en": "Rwandan Franc"},
    "SAR": {"ua": "Саудівський ріял", "en": "Saudi Riyal"},
    "SBD": {"ua": "Долар Соломонових островів", "en": "Solomon Islands Dollar"},
    "SCR": {"ua": "Сейшельська рупія", "en": "Seychellois Rupee"},
    "SDG": {"ua": "Суданський фунт", "en": "Sudanese Pound"},
    "SEK": {"ua": "Шведська крона", "en": "Swedish Krona"},
    "SGD": {"ua": "Сінгапурський долар", "en": "Singapore Dollar"},
    "SLL": {"ua": "Сьєрра-леонський леоне", "en": "Sierra Leonean Leone"},
    "SOS": {"ua": "Сомалійський шилінг", "en": "Somali Shilling"},
    "SRD": {"ua": "Суринамський долар", "en": "Surinamese Dollar"},
    "SYP": {"ua": "Сирійський фунт", "en": "Syrian Pound"},
    "SZL": {"ua": "Свазілендський лілангені", "en": "Swazi Lilangeni"},
    "THB": {"ua": "Таїландський бат", "en": "Thai Baht"},
    "TJS": {"ua": "Таджицький сомоні", "en": "Tajikistani Somoni"},
    "TMT": {"ua": "Туркменський манат", "en": "Turkmenistani Manat"},
    "TND": {"ua": "Туніський динар", "en": "Tunisian Dinar"},
    "TOP": {"ua": "Тонганська паанга", "en": "Tongan Paʻanga"},
    "TRY": {"ua": "Турецька ліра", "en": "Turkish Lira"},
    "TTD": {"ua": "Долар Трінідаду і Тобаго", "en": "Trinidad and Tobago Dollar"},
    "TWD": {"ua": "Новий тайванський долар", "en": "New Taiwan Dollar"},
    "TZS": {"ua": "Танзанійський шилінг", "en": "Tanzanian Shilling"},
    "UAH": {"ua": "Українська гривня", "en": "Ukrainian Hryvnia"},
    "UGX": {"ua": "Угандійський шилінг", "en": "Ugandan Sh"}
};